FROM rust:1.66.1
WORKDIR /app
RUN rustup target add x86_64-unknown-linux-musl
RUN rustup component add rustfmt
RUN cargo install cargo-edit cargo-watch cargo-make
RUN cargo install dioxus-cli
RUN cargo install --locked trunk